// Date extrase din "amb_clinic-lista-furnizori-in-contract_-_SIBIU.pdf"
// Lista furnizorilor de servicii medicale de specialitate din ambulatoriul
// pentru specialitati clinice in contract cu CAS Sibiu, la 01.05.2026
// + servicii conexe (psihologi, kinetoterapeuti) din lista-servicii-conexe-01-07-2025
const DATA_UPDATED = "01.05.2026 (medici) / 01.07.2025 (servicii conexe)";
const DATA_SOURCE = "Casa de Asigurari de Sanatate Sibiu (CNAS) - documente oficiale incarcate manual";

const CLINICS = {
  "alexa-og": { name: "Cabinet Alexa Delia-Alexandra (OG)", address: "Sos. Alba Iulia, nr. 50, et. I, ap. 2, Sibiu", phone: "0741110816" },
  "arcada": { name: "Arcada Clinic SRL", address: "Str. Barsei, bl. 8, Sibiu", phone: "0745514696" },
  "aria": { name: "Aria Clinic SRL", address: "Sos. Alba Iulia, nr. 100, Sibiu", phone: "0269-227773" },
  "ban-psih": { name: "Cabinet Ban Cosmina (Psihiatrie)", address: "Str. Closca, nr. 2, ap. 19, Medias", phone: "0744492379" },
  "beldean": { name: "Beldean Med SRL", address: "Str. Ion Neculce, Sibiu", phone: "0269-243833" },
  "bodea-ped": { name: "Cabinet Bodea Raluca Simona (Pediatrie)", address: "Str. Rahovei, bl. 57, ap. 3, Sibiu", phone: "0369-429481" },
  "bogdan-diabet": { name: "Cabinet Bogdan Mirela (Diabet)", address: "Str. Cindrelu, nr. 47, Cisnadie / Str. Spitalului, nr. 10, Agnita", phone: "0745617260" },
  "benefic": { name: "Centrul Medical Benefic SRL", address: "Str. Valea Mare, nr. 8, ap. 5, Sibiu / Str. 1 Decembrie, nr. 23, ap. 15, Medias", phone: "0269-214040" },
  "burian-endo": { name: "Cabinet Burian Adriana (Endocrinologie)", address: "Str. Closca, nr. 2, Medias", phone: "0269-831399" },
  "burlacu-ped": { name: "Cabinet Burlacu Iurie (Pediatrie)", address: "Str. Brazilor, nr. 1, sc. B, ap. 5, Sibiu", phone: "0369-816383" },
  "calcatinge-onco": { name: "Cabinet Calcatinge Maria Diana (Oncologie)", address: "Str. Closca, nr. 2, ap. 41, Medias", phone: "0269-834534" },
  "cardiolab": { name: "Cardiolab SRL", address: "Str. Ion Agarbiceanu, nr. 11, Sibiu", phone: "0749662220" },
  "cardiowellness": { name: "Cardiowellness SRL", address: "Str. Salajului, nr. 7, Sibiu", phone: "0722885560" },
  "praxismed": { name: "Centrul Medical Praxismed SRL", address: "Str. Stefan cel Mare, nr. 47, ap. 4, Sibiu / Str. Spitalului, nr. 29, Saliste", phone: "0747560994" },
  "stejari": { name: "Centrul Medical Stejari SRL", address: "Str. Goraslau, nr. 1, ap. 5-6, Sibiu", phone: "0369-444189" },
  "stanila": { name: "Centrul Medical Dr. Stanila SRL", address: "Str. Semaforului, nr. 4, Sibiu", phone: "0269-436480" },
  "sanogyn": { name: "Centrul Medical Sanogyn SRL", address: "Str. N. Iorga, nr. 50A, Sibiu", phone: "0766669065" },
  "unirea": { name: "Centrul Medical Unirea SRL", address: "Str. Emil Cioran, nr. 6, Sibiu", phone: "0722182487" },
  "polisano": { name: "Clinica Polisano SRL", address: "Str. Izvorului, nr. 1A, Sibiu / Str. B-dul Mihai Viteazu, nr. 4A, Sibiu / Str. Constitutiei, bl. 24, Sibiu", phone: "0269-234487 / 0269-234486" },
  "rogojanu": { name: "Complex Medical Dr. Rogojanu Aurel SRL", address: "Str. Horea, nr. 2A, Avrig", phone: "0269-523276" },
  "diaverum": { name: "Diaverum Romania SRL", address: "Str. Distributiei, nr. 32, Sibiu / Str. I.C. Bratianu, nr. 26, Medias", phone: "0269-219183" },
  "diaproct": { name: "Diaproct Sibiu SRL", address: "Str. Rusciorului, nr. 18, Sibiu", phone: "0735545530" },
  "dermatop": { name: "Dermatop SRL", address: "Str. Gh. Soima, nr. 8, bl. R1, ap. 3, Sibiu", phone: "0724307495" },
  "chicea-neuro": { name: "Cabinet Dr. Chicea Iulia-Oana (Neurologie)", address: "Str. Calea Poplacii, nr. 44B, ap. 2, Sibiu", phone: "0748799224" },
  "dwderma": { name: "DW Derma SRL", address: "Str. X, nr. 41, Cristian", phone: "0769642245" },
  "fizioplus": { name: "Centrul Medical Fizio Plus SRL", address: "Str. P-ta Prahovei, nr. 16, parter, ap. 17A, Sibiu", phone: "0269-206204" },
  "gensan": { name: "Gensan SRL", address: "Str. Grigore Alexandrescu, nr. 1, Sibiu", phone: "0269-239333" },
  "gyndia": { name: "Gyndia Nova SRL", address: "B-dul C. Coposu, nr. 10, Sibiu", phone: "0770157807" },
  "holhos": { name: "Holhos Optic Line SRL", address: "B-dul Vasile Milea, bl. 10, sc. B, ap. 17, Sibiu / Str. I. Gh. Duca, nr. 32, Medias", phone: "0735225915" },
  "mimd": { name: "MIMD Suport Medical SRL", address: "Sos. Sibiului, nr. 55, Medias", phone: "0744706944" },
  "lucas": { name: "Lucas Medical - Calea Dumbravii", address: "Calea Dumbravii, nr. 111, et. P, ap. SP2, Sibiu", phone: "0377702881" },
  "interecomed": { name: "Interecomed SRL", address: "Str. Tesatorilor, nr. 1, bl. 1, Cisnadie", phone: "0369-420320" },
  "glucostat": { name: "Lucas Medical - Str. Constitutiei", address: "Str. Constitutiei, nr. 1, bl. 1, ap. 17, parter, Sibiu", phone: "0746255717 / 0763054455" },
  "microfit": { name: "Microfit SRL", address: "Str. Serbota, nr. 8, Sibiu", phone: "0740205405" },
  "marginean-orl": { name: "Cabinet Marginean I. Ghe. - ORL Sanomed", address: "Str. Dr. Ioan Ratiu, nr. 4, Sibiu", phone: "0722735272" },
  "marinache-ped": { name: "Cabinet Marinache Luminita (Pediatrie)", address: "Str. Closca, nr. 2, Medias", phone: "0369-449550" },
  "medica": { name: "Medica SRL", address: "Calea Dumbravii, nr. 107, Sibiu", phone: "0269-212079" },
  "misanmed": { name: "Misan Med SRL", address: "Str. Hipodromului, nr. 3B, Sibiu", phone: "0269-212146" },
  "moisin-npi": { name: "Cabinet Moisin Lucia Elena (Neurologie/Psihiatrie Pediatrica)", address: "Str. Rahovei, nr. 29, ap. 46, Sibiu", phone: "0269-447548" },
  "naturapeutica": { name: "Naturapeutica Med SRL", address: "Str. Cindrelu, nr. 47, corp C1, et. I, ap. 16, Cisnadie", phone: "0722692050" },
  "neurobrain": { name: "Neurobrain Cliniq SRL", address: "Str. Cristian, nr. 15, Sibiu", phone: "0726576161" },
  "noemi": { name: "Noemi Med SRL", address: "Str. Horea, nr. 21, Medias", phone: "0773895117" },
  "oancea-pneumo": { name: "Cabinet Oancea Maria (Pneumologie)", address: "Str. Closca, nr. 2, Medias", phone: "0751244600" },
  "octasan": { name: "Octasan-Med SRL", address: "Sos. Alba Iulia, nr. 50A, et. I, ap. 2, Sibiu", phone: "0751211282" },
  "ophta": { name: "Ophta Consult SRL", address: "Str. N. Iorga, nr. 50A, Sibiu", phone: "0369-435803" },
  "popa-vlad-oft": { name: "Cabinet Popa Paul Vlad (Oftalmologie)", address: "Str. Iacob Bologa, nr. 8, sc. B, parter, ap. SP4, Sibiu", phone: "0773706118" },
  "orastean": { name: "Cabinet Orastean Ovidiu Ioan (Psihiatrie)", address: "Str. N. Iorga, nr. 50, et. 2, ap. 18, Sibiu", phone: "0756596950" },
  "platin": { name: "Platin Healthmed SRL", address: "Str. Aleea Rosiorilor, nr. 12, Sibiu", phone: "0269-212146" },
  "sfmihail": { name: "Policlinica Sf. Mihail SRL", address: "Str. Mihail Kogalniceanu, nr. 1, Sibiu", phone: "0773380486" },
  "psimed": { name: "Psi Med SRL", address: "Str. Aleea Rosiorilor, nr. 2B, ap. 2, Sibiu", phone: "0741516543" },
  "psihoconcept": { name: "Psihoconcept Med SRL", address: "Str. Semaforului, nr. 24, Sibiu / Str. Closca, nr. 2, Medias / Selimbar / Ocna Sibiului", phone: "0745688523" },
  "proctoven": { name: "Proctoven SRL", address: "Str. Rusciorului, nr. 18, Sibiu", phone: "0735545530" },
  "relivemed": { name: "Relivemed SRL", address: "Str. Doamna Stanca, nr. 5, ap. 1, Selimbar", phone: "0364091510" },
  "rmn": { name: "RMN Diagnostica SRL", address: "Str. Somesului, nr. 19, Sibiu / Agnita / Medias", phone: "0269-243121" },
  "spital-pediatrie": { name: "Spitalul Clinic de Pediatrie Sibiu", address: "Str. Transilvaniei, nr. 2-4 / Str. Ghe. Baritiu, nr. 1-3 / Str. Pompeiu Onofreiu, nr. 2-4, Sibiu", phone: "0269-230260" },
  "scju": { name: "Spitalul Clinic Judetean de Urgenta Sibiu", address: "B-dul C. Coposu, nr. 2-4, Sibiu", phone: "0269-215050" },
  "spital-pneumo": { name: "Spitalul de Pneumoftiziologie Sibiu", address: "Str. Aleea Filozofilor, nr. 3-5, Sibiu", phone: "0269-210979" },
  "spital-psih": { name: "Spitalul de Psihiatrie Sibiu", address: "Str. Dr. D-tru Bagdasar, nr. 12, Sibiu", phone: "0269-215680" },
  "spital-cf": { name: "Spitalul General CF Sibiu", address: "Str. C. Noica, nr. 21, Sibiu", phone: "0269-213163" },
  "spital-medias": { name: "Spitalul Municipal Medias", address: "Str. Closca, nr. 2, Medias", phone: "0269-842550" },
  "spital-agnita": { name: "Spitalul Orasenesc Agnita", address: "Str. Spitalului, nr. 10, Agnita", phone: "0269-510002" },
  "spital-cisnadie": { name: "Spitalul Orasenesc Cisnadie", address: "Str. Bailor, nr. 27, Cisnadie", phone: "0369-105102" },
  "turcu-dv": { name: "Cabinet Turcu Teodora (Dermato-venerologie)", address: "Str. Closca, nr. 2, Medias", phone: "0269-832363" },
  "todan-dv": { name: "Cabinet Dr. Todan Liliana Elena (Dermato-venerologie)", address: "Str. Closca, nr. 2, ap. 16, Medias", phone: "0369420427" },
  "unimed": { name: "Unimed SRL", address: "Str. P-ta Prahovei, nr. 18, sc. A, parter, ap. 35, Sibiu", phone: "0269-234203" },
  "veres-diabet": { name: "Cabinet Veres Oana (Diabet)", address: "Str. Closca, nr. 2, Medias", phone: "0369-455289" },
  "prosana": { name: "Clinica Prosana", address: "Str. Marasti, nr. 6, Sibiu", phone: "0269-233293 / 0787810043" },
  "costache-barb": { name: "Cabinet Dr. Costache-Barb Cristina (Diabet)", address: "Str. Ludus, nr. 5, ap. II, parter, Sibiu", phone: "0727036018" },
  "mester-ped": { name: "Cabinet Dr. Mester Elena Lavinia (Pediatrie)", address: "Str. Cindrelu, nr. 47, sc. B, ap. 9-10, Cisnadie", phone: "0745591366" },
};

// type: "medic" | "psiholog" | "kinetoterapeut" | "fizioterapeut"
const PEOPLE = [
  // --- ALEXA DELIA OG ---
  { n: "Alexa Delia-Alexandra", s: "Obstetrica-Ginecologie", g: "Specialist", c: "alexa-og", t: "medic" },

  // --- ARCADA CLINIC ---
  { n: "Teodoru Cosmin Adrian", s: "Oftalmologie", g: "Primar", c: "arcada", t: "medic" },
  { n: "Brehari Larisa Elena", s: "Oftalmologie", g: "Specialist", c: "arcada", t: "medic" },
  { n: "Feiereisz Andrada Ioana", s: "Oftalmologie", g: "Specialist", c: "arcada", t: "medic" },
  { n: "Cerghedean Florea Maria Emilia", s: "Oftalmologie", g: "Specialist", c: "arcada", t: "medic" },
  { n: "Bolta Alexandra Florina", s: "Medicina Interna", g: "Specialist", c: "arcada", t: "medic" },
  { n: "Feiereisz Alin Iulian", s: "Medicina Interna", g: "Specialist", c: "arcada", t: "medic" },
  { n: "Ilies Diana Luminita", s: "Psihiatrie", g: "Specialist", c: "arcada", t: "medic" },
  { n: "Coroeanu Andrada Elena", s: "Neurologie", g: "Specialist", c: "aria", t: "medic" },
  { n: "Mutu Cosmin", s: "Neurologie", g: "Primar", c: "aria", t: "medic" },
  { n: "Paraschiva Victoria", s: "Chirurgie Generala", g: "Specialist", c: "aria", t: "medic" },
  { n: "Picu Alexandru Cristian", s: "Dermato-venerologie", g: "Specialist", c: "aria", t: "medic" },
  { n: "Iancu Bianca Maria", s: "Recuperare, Medicina Fizica si Balneologie", g: "Specialist", c: "aria", t: "medic" },
  { n: "Birsan Alexandru", s: "Recuperare, Medicina Fizica si Balneologie", g: "Specialist", c: "aria", t: "medic" },

  // --- BAN COSMINA ---
  { n: "Ban Cosmina", s: "Psihiatrie", g: "Primar", c: "ban-psih", t: "medic" },

  // --- BELDEAN MED ---
  { n: "Beldean Luminita", s: "Endocrinologie", g: "Primar", c: "beldean", t: "medic" },

  // --- BODEA PEDIATRIE ---
  { n: "Bodea Raluca", s: "Pediatrie", g: "Primar", c: "bodea-ped", t: "medic" },

  // --- BOGDAN MIRELA DIABET ---
  { n: "Bogdan Mirela", s: "Diabet, nutritie si boli metabolice", g: "Primar", c: "bogdan-diabet", t: "medic" },

  // --- CENTRUL MEDICAL BENEFIC ---
  { n: "Bunea Adela", s: "Psihiatrie", g: "Primar", c: "benefic", t: "medic" },
  { n: "Aldea Henning Leon Corneliu", s: "Psihiatrie", g: "Specialist", c: "benefic", t: "medic" },
  { n: "Dumitru Georgiana Loredana", s: "Psihiatrie", g: "Specialist", c: "benefic", t: "medic" },
  { n: "Borodea Mariana", s: "Psiholog", g: "-", c: "benefic", t: "psiholog" },
  { n: "Streza Teodora Cristina", s: "Psiholog", g: "-", c: "benefic", t: "psiholog" },

  // --- BURIAN ENDOCRINOLOGIE ---
  { n: "Burian Adriana", s: "Endocrinologie", g: "Primar", c: "burian-endo", t: "medic" },

  // --- BURLACU PEDIATRIE ---
  { n: "Burlacu Iurie", s: "Pediatrie", g: "Primar", c: "burlacu-ped", t: "medic" },

  // --- CALCATINGE ONCOLOGIE ---
  { n: "Calcatinge Maria Diana", s: "Oncologie", g: "Primar", c: "calcatinge-onco", t: "medic" },

  // --- CARDIOLAB ---
  { n: "Podar Carmen Monica", s: "Cardiologie", g: "Specialist", c: "cardiolab", t: "medic" },

  // --- CARDIOWELLNESS ---
  { n: "Batar Sergiu Constantin", s: "Cardiologie", g: "Specialist", c: "cardiowellness", t: "medic" },

  // --- CENTRUL MEDICAL PRAXISMED ---
  { n: "Sfintu Ana", s: "Neurologie", g: "Specialist", c: "praxismed", t: "medic" },
  { n: "Boga Mirela", s: "Psihiatrie", g: "Specialist", c: "praxismed", t: "medic" },
  { n: "Boga Zeno Adrian", s: "Psihiatrie", g: "Specialist", c: "praxismed", t: "medic" },
  { n: "Serb Silvana Elena", s: "Psiholog", g: "-", c: "praxismed", t: "psiholog" },
  { n: "Catalinoiu Alexandra Loredana", s: "Medicina Fizica si de Reabilitare", g: "-", c: "praxismed", t: "kinetoterapeut" },
  { n: "Fagarasi Timea", s: "Medicina Fizica si de Reabilitare", g: "-", c: "praxismed", t: "kinetoterapeut" },

  // --- CENTRUL MEDICAL STEJARI ---
  { n: "Rusu Vlad", s: "Oftalmologie", g: "Primar", c: "stejari", t: "medic" },
  { n: "Florescu Mihaela", s: "Oftalmologie", g: "Primar", c: "stejari", t: "medic" },
  { n: "Botezan Andreea", s: "Oftalmologie", g: "Primar", c: "stejari", t: "medic" },
  { n: "Cretu Andreea Maria", s: "Oftalmologie", g: "Specialist", c: "stejari", t: "medic" },
  { n: "Gheban Aura Florica", s: "Psiholog", g: "-", c: "stejari", t: "psiholog" },

  // --- CENTRUL MEDICAL STANILA ---
  { n: "Stanila Dan Mircea", s: "Oftalmologie", g: "Primar", c: "stanila", t: "medic" },
  { n: "Stanila Alina", s: "Oftalmologie", g: "Primar", c: "stanila", t: "medic" },
  { n: "Soceanu Emilia Carmen", s: "Neurologie", g: "Primar", c: "stanila", t: "medic" },
  { n: "Chircus Andreea Cristina", s: "Psihiatrie", g: "Specialist", c: "stanila", t: "medic" },

  // --- CENTRUL MEDICAL SANOGYN ---
  { n: "Colceriu Andreea Maria", s: "Pediatrie", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Dodu Roxana Anamaria", s: "Psihiatrie", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Lebada Ioana Codruta", s: "Endocrinologie", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Tichindeleanu Nora Luminita", s: "Endocrinologie", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Mitea Raluca Daria", s: "Cardiologie", g: "Primar", c: "sanogyn", t: "medic" },
  { n: "Ungureanu Madalina", s: "ORL", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Dinu Ion", s: "Alergologie", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Dragoe Gina", s: "Endocrinologie", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Butica Delia", s: "Endocrinologie", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Harangus Mihai", s: "Cardiologie", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Matei Cristina Elena", s: "Chirurgie Generala", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Popentiu Adrian", s: "Chirurgie Generala", g: "Primar", c: "sanogyn", t: "medic" },
  { n: "Diaconu Denisa Elena", s: "Dermato-venerologie", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Galatan Simona", s: "Diabet, nutritie si boli metabolice", g: "Primar", c: "sanogyn", t: "medic" },
  { n: "Aldea Florina Elena", s: "Medicina Interna", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Gheorghiu Aliona", s: "Hematologie", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Capalnas Roxana Maria", s: "Obstetrica-Ginecologie", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Cimpean Tulea Andreea Alexandra", s: "Obstetrica-Ginecologie", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Oprea Adela", s: "Obstetrica-Ginecologie", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Ciuta Daniel", s: "Ortopedie", g: "Primar", c: "sanogyn", t: "medic" },
  { n: "Nemes Frum Daniela", s: "Neurologie", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Cazacu Ioana Delia", s: "Psihiatrie", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Cichi Mariana Lavinia", s: "Diabet, nutritie si boli metabolice", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Rau Ramona Teodora", s: "Cardiologie", g: "Specialist", c: "sanogyn", t: "medic" },
  { n: "Stoichita Stefania Lidia", s: "Pediatrie", g: "Specialist", c: "sanogyn", t: "medic" },

  // --- CENTRUL MEDICAL UNIREA ---
  { n: "Pumnea Pia Manuela", s: "Medicina Interna / Hematologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Abagiu Madalina", s: "Medicina Interna", g: "Primar", c: "unirea", t: "medic" },
  { n: "Tiurean Maria Luiza", s: "Medicina Interna", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Muntean Alina", s: "Medicina Interna", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Copaceanu Adelina Liana", s: "Medicina Interna", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Proteasa Andreea Simona", s: "Boli Infectioase", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Dobrin Ruxandra", s: "Cardiologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Mocanu Lorena Camelia", s: "Cardiologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Ristea Ruxandra Paula", s: "Endocrinologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Noor Cristina", s: "Hematologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Talau Raul Doru", s: "Psihiatrie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Bran Liviu Catalin", s: "Oftalmologie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Moroti Adrian Petru", s: "Oftalmologie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Gligor Ovidiu Horia", s: "Obstetrica-Ginecologie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Filip Greti", s: "Obstetrica-Ginecologie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Lup Nicoleta Alma", s: "Obstetrica-Ginecologie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Condrea Teodora Maria", s: "Obstetrica-Ginecologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Cretu Raluca Maria", s: "Obstetrica-Ginecologie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Sora Livia Ileana", s: "Obstetrica-Ginecologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Maris Maria Ricarda", s: "Obstetrica-Ginecologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Dedean Ioana Diana", s: "Oncologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Ecea Radu", s: "Oncologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Nimirceag Victor Marian", s: "Oncologie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Sinea Laura Olimpia", s: "Oncologie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Molnar Andreea Cristina", s: "Oncologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Vonica Razvan Constantin", s: "Oncologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Chelcea Daniel", s: "ORL", g: "Primar", c: "unirea", t: "medic" },
  { n: "Opris Aura Maria", s: "ORL", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Bacalu Victor", s: "Radioterapie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Stahiescu Raluca", s: "Radioterapie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Mustata Maria", s: "Radioterapie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Coman Aurel", s: "Chirurgie Generala", g: "Primar", c: "unirea", t: "medic" },
  { n: "Kiss Lorant", s: "Chirurgie Generala", g: "Primar", c: "unirea", t: "medic" },
  { n: "Noor Hassan", s: "Chirurgie Generala", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Costea Ciprian Ioan", s: "Chirurgie Generala", g: "Primar", c: "unirea", t: "medic" },
  { n: "Tohatan Calin Cristian", s: "Chirurgie Generala", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Bartos Laura Iulia", s: "Ortopedie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Faur Calin Andrei", s: "Urologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Stanciu Loredana Ramona", s: "Cardiologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Cojan Radu", s: "Cardiologie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Florescu Nicolae", s: "Cardiologie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Purcar Oana", s: "Cardiologie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Sirbu Prisecaru Raluca Vasilica", s: "Cardiologie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Vacariu Victor", s: "Cardiologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Costea Raluca Maria Diana", s: "Cardiologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Craciun Roxana Elena", s: "Chirurgie Generala", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Matei Claudiu", s: "Neurochirurgie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Gherman Joseph", s: "Neurochirurgie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Nistor Ioana Sofia", s: "Neurochirurgie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Talau Mariana", s: "Neurologie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Filip Dan", s: "Neurologie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Nedelcu Mihaela Elena", s: "Reumatologie", g: "Primar", c: "unirea", t: "medic" },
  { n: "Ionescu Croitoru Mihaela Andreea", s: "Dermato-venerologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Dutu Silvana Bianca", s: "Dermato-venerologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Trailovic Zvomko", s: "Dermato-venerologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Micu Alexandra Ioana", s: "Urologie", g: "Specialist", c: "unirea", t: "medic" },
  { n: "Pirvut Mircea Valentin", s: "Urologie", g: "Primar", c: "unirea", t: "medic" },

  // --- CLINICA POLISANO ---
  { n: "Sora Livia Ileana", s: "Obstetrica-Ginecologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Cretu Raluca Maria", s: "Obstetrica-Ginecologie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Maris Maria Ricarda", s: "Obstetrica-Ginecologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Condrea Teodora Maria", s: "Obstetrica-Ginecologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Gligor Ovidiu Horia", s: "Obstetrica-Ginecologie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Marginean Gelu Cristian", s: "Ortopedie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Draghici Grecu Ioana Paula", s: "Oftalmologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Rau Ramona Teodora", s: "Cardiologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Munteanu Daniela Alexandra", s: "Chirurgie Generala", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Gheorghe Cristiana Georgiana", s: "Chirurgie Pediatrica", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Telehuz Daniela", s: "Endocrinologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Seicaru Elena Maria", s: "Endocrinologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Muntean Alina", s: "Medicina Interna", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Copaceanu Adelina Liana", s: "Medicina Interna", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Sadeanu Laura Carmen", s: "Medicina Interna", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Constantin Alexandra", s: "Pediatrie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Vacariu Daniela", s: "Pediatrie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Plukchi Iulia", s: "Gastroenterologie Pediatrica", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Giurgiu Iulia", s: "Diabet, nutritie si boli metabolice", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Carcalici Ioan Radu", s: "Neurologie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Plesca Adelina Ioana", s: "Neurologie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Fulea Teodora Ioana", s: "Medicina Fizica si Reabilitare", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Bartos Tiberiu Ioan", s: "Kinetoterapie", g: "-", c: "polisano", t: "kinetoterapeut" },
  { n: "Mocanu Lorena Camelia", s: "Cardiologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Mitea Raluca Daria", s: "Cardiologie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Pumnea Pia Manuela", s: "Medicina Interna / Hematologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Abagiu Madalina", s: "Medicina Interna", g: "Primar", c: "polisano", t: "medic" },
  { n: "Tiurean Maria Luiza", s: "Medicina Interna", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Proteasa Andreea Simona", s: "Boli Infectioase", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Dobrin Ruxandra", s: "Cardiologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Ristea Ruxandra Paula", s: "Endocrinologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Noor Cristina", s: "Hematologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Talau Raul Doru", s: "Psihiatrie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Bran Liviu Catalin", s: "Oftalmologie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Moroti Adrian Petru", s: "Oftalmologie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Filip Greti", s: "Obstetrica-Ginecologie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Lup Nicoleta Alma", s: "Obstetrica-Ginecologie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Dedean Ioana Diana", s: "Oncologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Ecea Radu", s: "Oncologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Nimirceag Victor Marian", s: "Oncologie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Sinea Laura Olimpia", s: "Oncologie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Molnar Andreea Cristina", s: "Oncologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Vonica Razvan Constantin", s: "Oncologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Chelcea Daniel", s: "ORL", g: "Primar", c: "polisano", t: "medic" },
  { n: "Opris Aura Maria", s: "ORL", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Bacalu Victor", s: "Radioterapie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Stahiescu Raluca", s: "Radioterapie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Mustata Maria", s: "Radioterapie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Coman Aurel", s: "Chirurgie Generala", g: "Primar", c: "polisano", t: "medic" },
  { n: "Kiss Lorant", s: "Chirurgie Generala", g: "Primar", c: "polisano", t: "medic" },
  { n: "Noor Hassan", s: "Chirurgie Generala", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Costea Ciprian Ioan", s: "Chirurgie Generala", g: "Primar", c: "polisano", t: "medic" },
  { n: "Tohatan Calin Cristian", s: "Chirurgie Generala", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Craciun Roxana Elena", s: "Chirurgie Generala", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Bartos Laura Iulia", s: "Ortopedie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Faur Calin Andrei", s: "Urologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Matei Claudiu", s: "Neurochirurgie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Gherman Joseph", s: "Neurochirurgie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Nistor Ioana Sofia", s: "Neurochirurgie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Talau Mariana", s: "Neurologie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Filip Dan", s: "Neurologie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Nedelcu Mihaela Elena", s: "Reumatologie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Ionescu Croitoru Mihaela Andreea", s: "Dermato-venerologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Dutu Silvana Bianca", s: "Dermato-venerologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Trailovic Zvomko", s: "Dermato-venerologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Micu Alexandra Ioana", s: "Urologie", g: "Specialist", c: "polisano", t: "medic" },
  { n: "Pirvut Mircea Valentin", s: "Urologie", g: "Primar", c: "polisano", t: "medic" },
  { n: "Piringer Serban Anda", s: "Psiholog", g: "-", c: "polisano", t: "psiholog" },
  { n: "Ionascu Elena", s: "Psiholog", g: "-", c: "polisano", t: "psiholog" },
  { n: "Mares Dana Daniela", s: "Psiholog", g: "-", c: "polisano", t: "psiholog" },

  // --- COMPLEX MEDICAL DR. ROGOJANU ---
  { n: "Itu Ioana Monica", s: "Psihiatrie", g: "Specialist", c: "rogojanu", t: "medic" },

  // --- DIAVERUM ---
  { n: "Fociuc Gabriela", s: "Nefrologie", g: "Primar", c: "diaverum", t: "medic" },
  { n: "Agapi Elena", s: "Nefrologie", g: "Primar", c: "diaverum", t: "medic" },
  { n: "Teodor Elena Romfilia", s: "Nefrologie", g: "Primar", c: "diaverum", t: "medic" },
  { n: "Moro Daniela Carmen", s: "Nefrologie", g: "Primar", c: "diaverum", t: "medic" },
  { n: "Stirbu Marcela", s: "Nefrologie", g: "Specialist", c: "diaverum", t: "medic" },
  { n: "Ienciu Cristina Ionela", s: "Nefrologie", g: "Specialist", c: "diaverum", t: "medic" },
  { n: "Railean Eugenia", s: "Nefrologie", g: "Primar", c: "diaverum", t: "medic" },

  // --- DIAPROCT ---
  { n: "Tanasescu Denisa Ioana", s: "Diabet, nutritie si boli metabolice", g: "Specialist", c: "diaproct", t: "medic" },

  // --- DERMATOP ---
  { n: "Rotaru Maria", s: "Dermato-venerologie", g: "Primar", c: "dermatop", t: "medic" },

  // --- CHICEA IULIA-OANA NEUROLOGIE ---
  { n: "Chicea Iulia-Oana", s: "Neurologie", g: "Primar", c: "chicea-neuro", t: "medic" },

  // --- DW DERMA ---
  { n: "Hatman Cristina Andrada", s: "Dermato-venerologie", g: "Specialist", c: "dwderma", t: "medic" },

  // --- CENTRUL MEDICAL FIZIO PLUS ---
  { n: "Domnariu Carmen Daniela", s: "Recuperare, Medicina Fizica si Balneologie", g: "Primar", c: "fizioplus", t: "medic" },
  { n: "Kosc Mircea Marian", s: "Kinetoterapie", g: "-", c: "fizioplus", t: "kinetoterapeut" },
  { n: "Fagarasi Timea", s: "Kinetoterapie", g: "-", c: "fizioplus", t: "kinetoterapeut" },

  // --- GENSAN ---
  { n: "Mara Alina Elena", s: "Alergologie", g: "Primar", c: "gensan", t: "medic" },
  { n: "Muntean Iulia Roxana", s: "Diabet, nutritie si boli metabolice", g: "Primar", c: "gensan", t: "medic" },
  { n: "Arcomita Doina", s: "Diabet, nutritie si boli metabolice", g: "Specialist", c: "gensan", t: "medic" },
  { n: "Albu Laura Maria", s: "Endocrinologie", g: "Specialist", c: "gensan", t: "medic" },
  { n: "Cobirje Popa Geanina Mihaela", s: "Neurologie", g: "Primar", c: "gensan", t: "medic" },
  { n: "Mihai Minodora Eugenia", s: "Reumatologie", g: "Specialist", c: "gensan", t: "medic" },
  { n: "Dobra Andreea Nicoleta", s: "Psihiatrie", g: "Specialist", c: "gensan", t: "medic" },
  { n: "Ionascu Elena", s: "Psiholog", g: "-", c: "gensan", t: "psiholog" },
  { n: "Piringer Serban Anda", s: "Psiholog", g: "-", c: "gensan", t: "psiholog" },
  { n: "Mares Dana Daniela", s: "Psiholog", g: "-", c: "gensan", t: "psiholog" },
  { n: "Achim Ruxandra Ivona", s: "Chirurgie Plastica", g: "Specialist", c: "gensan", t: "medic" },
  { n: "Balan Andrada Monica", s: "Obstetrica-Ginecologie", g: "Specialist", c: "gensan", t: "medic" },
  { n: "Gherman Ioana Alexandra", s: "Obstetrica-Ginecologie", g: "Specialist", c: "gensan", t: "medic" },
  { n: "Achim Angela Teodora", s: "Cardiologie", g: "Specialist", c: "gensan", t: "medic" },
  { n: "Coman Vasile Liviu", s: "Psihiatrie Pediatrica", g: "Specialist", c: "gensan", t: "medic" },
  { n: "Palcu Florina", s: "Dermato-venerologie", g: "Primar", c: "gensan", t: "medic" },
  { n: "Barbu Alexandra", s: "Dermato-venerologie", g: "Specialist", c: "gensan", t: "medic" },
  { n: "Stefanescu Anisoara", s: "Medicina Fizica si Reabilitare", g: "Primar", c: "gensan", t: "medic" },

  // --- GYNDIA NOVA ---
  { n: "Nicolescu Georgiana", s: "Diabet, nutritie si boli metabolice", g: "Primar", c: "gyndia", t: "medic" },

  // --- HOLHOS OPTIC LINE ---
  { n: "Czika Alexandra", s: "Oftalmologie", g: "Specialist", c: "holhos", t: "medic" },

  // --- MIMD ---
  { n: "Vonica Flavia Maria", s: "Oftalmologie", g: "Specialist", c: "mimd", t: "medic" },

  // --- INTERECOMED ---
  { n: "Rezi Elena Cristina", s: "Medicina Interna", g: "Primar", c: "interecomed", t: "medic" },

  // --- GLUCO-STAT ---
  { n: "Costea Alexandru Georgian", s: "Cardiologie", g: "Specialist", c: "glucostat", t: "medic" },
  { n: "Iliescu Bianca Iliana", s: "Endocrinologie", g: "Specialist", c: "glucostat", t: "medic" },
  { n: "Draghici Ionela Diana", s: "Endocrinologie", g: "Specialist", c: "glucostat", t: "medic" },
  { n: "Chicea Iulia Oana", s: "Neurologie", g: "Primar", c: "glucostat", t: "medic" },
  { n: "Lita Anca Elena", s: "Psihiatrie", g: "Specialist", c: "glucostat", t: "medic" },
  { n: "Dumitrescu Roxana Monica", s: "Diabet, nutritie si boli metabolice", g: "Primar", c: "glucostat", t: "medic" },

  // --- MICROFIT ---
  { n: "Chicea Lucian", s: "Neurologie", g: "Primar", c: "microfit", t: "medic" },
  { n: "Lita Anca Elena", s: "Psihiatrie", g: "Specialist", c: "microfit", t: "medic" },

  // --- MARGINEAN ORL ---
  { n: "Marginean Ioan Ghe.", s: "ORL", g: "Primar", c: "marginean-orl", t: "medic" },

  // --- MARINACHE PEDIATRIE ---
  { n: "Marinache Luminita", s: "Pediatrie", g: "Primar", c: "marinache-ped", t: "medic" },

  // --- LUCAS MEDICAL (rand 33) ---
  { n: "Florescu Mihaela", s: "Oftalmologie", g: "Primar", c: "lucas", t: "medic" },
  { n: "Sirbu Cornelia", s: "Oftalmologie", g: "Specialist", c: "lucas", t: "medic" },

  // --- MEDICA SRL ---
  { n: "Matusa Ion Catalin", s: "Psihiatrie", g: "Specialist", c: "medica", t: "medic" },
  { n: "Popa Veronica", s: "Psihiatrie", g: "Specialist", c: "medica", t: "medic" },
  { n: "Zugravu Catalina Laura", s: "Endocrinologie", g: "Specialist", c: "medica", t: "medic" },
  { n: "Batar Florina Gabriela", s: "Cardiologie", g: "Primar", c: "medica", t: "medic" },
  { n: "Dobra Maria Castilia", s: "Chirurgie Generala", g: "Specialist", c: "medica", t: "medic" },
  { n: "Solomon Radu Crina Cristina", s: "Diabet, nutritie si boli metabolice", g: "Specialist", c: "prosana", t: "medic" },
  { n: "Gafton Ana Alina", s: "Dermato-venerologie", g: "Specialist", c: "medica", t: "medic" },
  { n: "Baldovin Ioana", s: "Dermato-venerologie", g: "Primar", c: "medica", t: "medic" },
  { n: "Moldovan Elena", s: "Psihiatrie", g: "Specialist", c: "medica", t: "medic" },
  { n: "Sas Alina Daniela", s: "Psihiatrie", g: "Primar", c: "medica", t: "medic" },
  { n: "Presecan Camelia", s: "Psihiatrie", g: "Specialist", c: "medica", t: "medic" },
  { n: "Szakacs Dana Silvia Mihaela", s: "Ortopedie", g: "Specialist", c: "medica", t: "medic" },
  { n: "Presecan Camelia", s: "Neurologie", g: "Specialist", c: "medica", t: "medic" },
  { n: "Fertu Ilariana Luciana", s: "Medicina Interna", g: "Specialist", c: "medica", t: "medic" },
  { n: "Tiurean Maria Luiza", s: "Medicina Interna", g: "Specialist", c: "medica", t: "medic" },
  { n: "Deutsch Laurentiu Tiberiu", s: "Urologie", g: "Primar", c: "medica", t: "medic" },
  { n: "Ionascu Elena", s: "Psiholog", g: "-", c: "medica", t: "psiholog" },
  { n: "Hirlea Camelia", s: "Psiholog", g: "-", c: "medica", t: "psiholog" },

  // --- MISAN MED ---
  { n: "Vasilache Veronica", s: "Cardiologie", g: "Primar", c: "misanmed", t: "medic" },
  { n: "Coldea Liliana", s: "Cardiologie", g: "Primar", c: "misanmed", t: "medic" },
  { n: "Lazar Florin Leontin", s: "Cardiologie", g: "Specialist", c: "misanmed", t: "medic" },
  { n: "Moscu Mario Bogdan", s: "Dermato-venerologie", g: "Primar", c: "misanmed", t: "medic" },
  { n: "Prodan Ioan", s: "Gastroenterologie", g: "Specialist", c: "misanmed", t: "medic" },
  { n: "Coman Daniela", s: "Gastroenterologie", g: "Specialist", c: "misanmed", t: "medic" },
  { n: "Dragomir Ionut Nicolae", s: "Medicina Interna", g: "Specialist", c: "misanmed", t: "medic" },
  { n: "Gutia Alexandru Emanuil", s: "Medicina Interna", g: "Primar", c: "misanmed", t: "medic" },
  { n: "Nedelcu Constantin Alexandru", s: "Chirurgie Generala", g: "Specialist", c: "misanmed", t: "medic" },
  { n: "Muntean Ciprian Nicolae", s: "Chirurgie Generala", g: "Primar", c: "misanmed", t: "medic" },
  { n: "Silivasan Eugen C-tin", s: "Chirurgie Generala", g: "Primar", c: "misanmed", t: "medic" },
  { n: "Antonie Gabriela", s: "ORL", g: "Specialist", c: "misanmed", t: "medic" },
  { n: "Deutsch Ioana Raluca", s: "Obstetrica-Ginecologie", g: "Specialist", c: "misanmed", t: "medic" },
  { n: "Badescu Tudor Mihai", s: "Obstetrica-Ginecologie", g: "Primar", c: "misanmed", t: "medic" },
  { n: "Teodorescu Elena Luisza", s: "Psihiatrie", g: "Specialist", c: "misanmed", t: "medic" },
  { n: "Constantin Elena", s: "Kinetoterapie", g: "-", c: "misanmed", t: "kinetoterapeut" },

  // --- MOISIN NPI ---
  { n: "Moisin Lucia Elena", s: "Neurologie Pediatrica / Psihiatrie Pediatrica", g: "Specialist", c: "moisin-npi", t: "medic" },

  // --- NATURAPEUTICA ---
  { n: "Burcea Roxana", s: "Psihiatrie", g: "Specialist", c: "naturapeutica", t: "medic" },

  // --- NEUROBRAIN CLINIQ ---
  { n: "Costea Simona Daniela", s: "Neurologie", g: "Primar", c: "neurobrain", t: "medic" },
  { n: "Mosorescu Ruxandra", s: "Neurologie", g: "Specialist", c: "neurobrain", t: "medic" },
  { n: "Albu Maria Mihaela", s: "Medicina Fizica si Reabilitare", g: "Specialist", c: "neurobrain", t: "medic" },
  { n: "Iacob Rares Florin", s: "Medicina Fizica si Reabilitare", g: "Specialist", c: "neurobrain", t: "medic" },
  { n: "Teodorescu Stefania", s: "Kinetoterapie", g: "-", c: "neurobrain", t: "kinetoterapeut" },
  { n: "Moldovan Alexandru", s: "Kinetoterapie", g: "-", c: "neurobrain", t: "kinetoterapeut" },
  { n: "Dorobantu Ion-Ovidiu", s: "Psihiatrie", g: "Specialist", c: "neurobrain", t: "medic" },
  { n: "Holerga Ioana Iuliana", s: "Psihiatrie", g: "Specialist", c: "neurobrain", t: "medic" },
  { n: "Duicu Rares", s: "Pneumologie", g: "Primar", c: "neurobrain", t: "medic" },
  { n: "Szabo Chiriac Evelyne Christine", s: "Pneumologie", g: "Specialist", c: "neurobrain", t: "medic" },
  { n: "Rajka Maria Andrea", s: "Medicina Interna", g: "Specialist", c: "neurobrain", t: "medic" },
  { n: "Dancu Radu George Sevastian", s: "Medicina Interna", g: "Specialist", c: "neurobrain", t: "medic" },
  { n: "Acaru Alexandra", s: "Psiholog", g: "-", c: "neurobrain", t: "psiholog" },
  { n: "Hirlea Camelia", s: "Psiholog", g: "-", c: "neurobrain", t: "psiholog" },

  // --- NOEMI MED ---
  { n: "Haus Laura", s: "Hematologie", g: "Specialist", c: "noemi", t: "medic" },
  { n: "Mihulecea Gheorghe", s: "Oncologie", g: "Primar", c: "noemi", t: "medic" },

  // --- OANCEA PNEUMOLOGIE ---
  { n: "Oancea Maria", s: "Pneumologie", g: "Primar", c: "oancea-pneumo", t: "medic" },

  // --- OCTASAN-MED ---
  { n: "Urluescu Madalina Loredana", s: "Cardiologie", g: "Primar", c: "octasan", t: "medic" },

  // --- OPHTA CONSULT ---
  { n: "Laslau Bianca Maria", s: "Oftalmologie", g: "Specialist", c: "ophta", t: "medic" },
  { n: "Pasca Bianca Maria", s: "Oftalmologie", g: "Primar", c: "ophta", t: "medic" },
  { n: "Santea Monica Cornelia", s: "Oftalmologie", g: "Primar", c: "ophta", t: "medic" },
  { n: "Cutean Iulia", s: "Oftalmologie", g: "Specialist", c: "ophta", t: "medic" },

  // --- POPA PAUL VLAD OFTALMOLOGIE ---
  { n: "Popa Paul Vlad", s: "Oftalmologie", g: "Specialist", c: "popa-vlad-oft", t: "medic" },

  // --- ORASTEAN PSIHIATRIE ---
  { n: "Orastean Ovidiu Ioan", s: "Psihiatrie", g: "Primar", c: "orastean", t: "medic" },

  // --- PLATIN HEALTHMED ---
  { n: "Stanimir Natalia Elena", s: "Dermato-venerologie", g: "Specialist", c: "platin", t: "medic" },
  { n: "Comaniciu Andra", s: "Gastroenterologie", g: "Specialist", c: "platin", t: "medic" },
  { n: "Arseniu Rares", s: "Pediatrie", g: "Specialist", c: "platin", t: "medic" },
  { n: "Oroian Cristina Gabriela", s: "Psihiatrie", g: "Primar", c: "platin", t: "medic" },
  { n: "Popa Monica Carmen", s: "Psihiatrie", g: "Primar", c: "platin", t: "medic" },
  { n: "Lazaroae Ana", s: "Neurologie", g: "Primar", c: "platin", t: "medic" },
  { n: "Zaica Svetlana", s: "Neurologie", g: "Specialist", c: "platin", t: "medic" },
  { n: "Lupean Laura Maria", s: "Endocrinologie", g: "Specialist", c: "platin", t: "medic" },
  { n: "Tichindeleanu Nora Luminita", s: "Endocrinologie", g: "Specialist", c: "platin", t: "medic" },
  { n: "Negrea Mihai Octavian", s: "Cardiologie", g: "Specialist", c: "platin", t: "medic" },
  { n: "Vulcu Raul Liviu", s: "Cardiologie", g: "Primar", c: "platin", t: "medic" },
  { n: "Dragulescu Stefania Larisa", s: "Endocrinologie", g: "Specialist", c: "platin", t: "medic" },
  { n: "Albu Maria Mihaela", s: "Medicina Interna", g: "Specialist", c: "platin", t: "medic" },
  { n: "Pumnea Pia Manuela", s: "Medicina Interna", g: "Specialist", c: "platin", t: "medic" },
  { n: "Batir Crestin Anisoara", s: "Obstetrica-Ginecologie", g: "Specialist", c: "platin", t: "medic" },
  { n: "Neagu Andrei Dorin", s: "Obstetrica-Ginecologie", g: "Specialist", c: "platin", t: "medic" },
  { n: "Ghisa Andreea", s: "Pediatrie", g: "Primar", c: "platin", t: "medic" },
  { n: "Predica Andreea Roxana", s: "Pediatrie", g: "Specialist", c: "platin", t: "medic" },
  { n: "Vasiu Cristina Florina", s: "Psihiatrie", g: "Specialist", c: "platin", t: "medic" },
  { n: "Coman Vasile Liviu", s: "Psihiatrie Pediatrica", g: "Specialist", c: "platin", t: "medic" },
  { n: "Al Kaddah Elena", s: "Psihiatrie Pediatrica", g: "Specialist", c: "platin", t: "medic" },
  { n: "Stroia Alexandra", s: "Medicina Fizica si Reabilitare", g: "Specialist", c: "platin", t: "medic" },
  { n: "Costinescu Anca", s: "Medicina Fizica si Reabilitare", g: "Specialist", c: "platin", t: "medic" },
  { n: "Moga Daniela", s: "Psiholog", g: "-", c: "platin", t: "psiholog" },
  { n: "Parvu Denisa Andrada", s: "Psiholog", g: "-", c: "platin", t: "psiholog" },

  // --- POLICLINICA SF. MIHAIL ---
  { n: "Trantor Andra Maria", s: "Psiholog", g: "-", c: "sfmihail", t: "psiholog" },
  { n: "Chera Oana Maria", s: "Psiholog", g: "-", c: "sfmihail", t: "psiholog" },
  { n: "Guta Mirela", s: "Fizioterapie", g: "-", c: "sfmihail", t: "fizioterapeut" },
  { n: "Dobrota Diana", s: "Fizioterapie", g: "-", c: "sfmihail", t: "fizioterapeut" },
  { n: "Hondor Stefania", s: "Fizioterapie", g: "-", c: "sfmihail", t: "fizioterapeut" },
  { n: "Milcioiu Ionut Radu", s: "Fizioterapie", g: "-", c: "sfmihail", t: "fizioterapeut" },
  { n: "Secelean Ana Ioana", s: "Psihiatrie", g: "Primar", c: "sfmihail", t: "medic" },
  { n: "Pacala Bogdan Marius", s: "Psihiatrie", g: "Primar", c: "sfmihail", t: "medic" },
  { n: "Leopold Delia", s: "Psihiatrie", g: "Primar", c: "sfmihail", t: "medic" },
  { n: "Sebu Iulia Teodora", s: "Psihiatrie", g: "Specialist", c: "sfmihail", t: "medic" },
  { n: "Ciobanu Anca Iulia", s: "Psihiatrie", g: "Specialist", c: "sfmihail", t: "medic" },
  { n: "Muntean Cosmina", s: "Psihiatrie", g: "Primar", c: "sfmihail", t: "medic" },
  { n: "Mitrea Felicia", s: "Psihiatrie", g: "Primar", c: "sfmihail", t: "medic" },
  { n: "Voulgaropoulos Agata Mirela", s: "Psihiatrie", g: "Primar", c: "sfmihail", t: "medic" },
  { n: "Sabau Bogdan Alin", s: "Psihiatrie", g: "Primar", c: "sfmihail", t: "medic" },
  { n: "Gruescu-Ionescu Andra Cristina", s: "Psihiatrie", g: "Specialist", c: "sfmihail", t: "medic" },
  { n: "Talpos Andreea Maria", s: "Gastroenterologie", g: "Specialist", c: "sfmihail", t: "medic" },
  { n: "Picu Andreea Maria", s: "Cardiologie", g: "Specialist", c: "sfmihail", t: "medic" },
  { n: "Dumneanu Alexandru", s: "Cardiologie", g: "-", c: "sfmihail", t: "medic" },

  // --- PSI MED ---
  { n: "Popa Lucia Maria", s: "Psiholog", g: "-", c: "psimed", t: "psiholog" },

  // --- PSIHOCONCEPT MED ---
  { n: "Mara Tomina", s: "Psiholog", g: "-", c: "psihoconcept", t: "psiholog" },
  { n: "Oltean Gabriela Raluca", s: "Psiholog", g: "-", c: "psihoconcept", t: "psiholog" },
  { n: "Filip Aurora Olimpia", s: "Psiholog", g: "-", c: "psihoconcept", t: "psiholog" },
  { n: "Tatu Anisoara", s: "Psiholog", g: "-", c: "psihoconcept", t: "psiholog" },

  // --- PROCTOVEN ---
  { n: "Talpos Andreea Maria", s: "Gastroenterologie", g: "Specialist", c: "proctoven", t: "medic" },
  { n: "Picu Andreea Maria", s: "Cardiologie", g: "Specialist", c: "proctoven", t: "medic" },
  { n: "Dumneanu Alexandru", s: "Cardiologie", g: "-", c: "proctoven", t: "medic" },

  // --- RELIVEMED ---
  { n: "Bocodi Mariana Corina", s: "Medicina Interna", g: "Primar", c: "relivemed", t: "medic" },

  // --- RMN DIAGNOSTICA (CAS) ---
  { n: "Bogdan Anca Catalina", s: "Cardiologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Puia Andreea Daniela", s: "Cardiologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Nistor Adrian Petru", s: "Cardiologie", g: "Primar", c: "rmn", t: "medic" },
  { n: "Onea Horea Laurentiu", s: "Cardiologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Tonch Cerbu Alexandra Kristine", s: "Cardiologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Verde Ioana Maria", s: "Endocrinologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Iosif Cristina Sofia", s: "Endocrinologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Patrinca Andrei", s: "Psihiatrie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Maruntel Dorina Irina", s: "Psihiatrie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Ghise Gheorghe", s: "Diabet, nutritie si boli metabolice", g: "Primar", c: "rmn", t: "medic" },
  { n: "Hilma Ana Maria", s: "Diabet, nutritie si boli metabolice", g: "Primar", c: "rmn", t: "medic" },
  { n: "Molnar Estera", s: "Dermato-venerologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Neagu Iuliana", s: "Dermato-venerologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Tincu Diana", s: "Dermato-venerologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Terec Sergiu Adrian", s: "Gastroenterologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Ganfalean Stefana", s: "Gastroenterologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Bunea Stefan", s: "Gastroenterologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Lupu Petria Alexandra Delia", s: "Medicina Interna", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Cotrus Florenta Venera", s: "Medicina Interna", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Streza Maria Camelia", s: "Medicina Interna", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Antal Elisabeta Andreea", s: "Hematologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Micu Nicolae Madalin", s: "Neurologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Teposu Bogdan Nicolae", s: "Neurologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Ghincea Marius Ionut", s: "Neurologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Marga Ioan", s: "Neurologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Tanase Alexandra", s: "Neurologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Luncasu Paula", s: "Obstetrica-Ginecologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Panta Vladia", s: "Obstetrica-Ginecologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Manta Tia Maria", s: "Obstetrica-Ginecologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Stuparoiu Vatau Adriana Emilia", s: "ORL", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Ermacov Liliana", s: "ORL", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Buta Diana Ioana", s: "Pneumologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Popescu Claudia Raluca", s: "Pneumologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Vulcu Andra Cecilia", s: "Pneumologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Gancea Alexandru C-tin", s: "Urologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Anghel Mic Alexandru Cristian", s: "Urologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Denghel Adriana", s: "Ortopedie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Popa Alexandru Darius", s: "Ortopedie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Sacarelis Alexis Vasilis", s: "Ortopedie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Corlaciu Iulia Alina", s: "Psihiatrie Pediatrica", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Acaru Alexandra", s: "Psiholog", g: "-", c: "rmn", t: "psiholog" },
  { n: "Hirlea Camelia", s: "Psiholog", g: "-", c: "rmn", t: "psiholog" },
  { n: "Micu Mihaela", s: "Diabet, nutritie si boli metabolice", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Negutescu Codruta Ioana", s: "Diabet, nutritie si boli metabolice", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Lei Sabina Alexandra", s: "Oncologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Valeanu Valeria Vioara", s: "Oncologie", g: "Primar", c: "rmn", t: "medic" },
  { n: "Muntean Cristina", s: "Oncologie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Tarcea Ioana Maria", s: "Pediatrie", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Ciora Adriana Petrica", s: "Medicina Fizica si Reabilitare", g: "Specialist", c: "rmn", t: "medic" },
  { n: "Luca Daniel Simion", s: "Medicina Fizica si Reabilitare", g: "Primar", c: "rmn", t: "medic" },
  { n: "Constantin Elena", s: "Kinetoterapie", g: "-", c: "rmn", t: "kinetoterapeut" },
  { n: "Csillag Andreea", s: "Alergologie", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Luca Mihaela Codruta", s: "Boli Infectioase", g: "Specialist", c: "spital-pediatrie", t: "medic" },
  { n: "Patru Rares Gheorghe", s: "Boli Infectioase", g: "Primar", c: "spital-pediatrie", t: "medic" },

  // --- RMN DIAGNOSTIC SI TRATAMENT ---
  { n: "Torge Susana Mihaela", s: "Boli Infectioase", g: "Specialist", c: "spital-pediatrie", t: "medic" },
  { n: "Hagau Asmaa Carla", s: "Cardiologie Pediatrica", g: "Specialist", c: "spital-pediatrie", t: "medic" },
  { n: "Berghea Neamtu Cristian", s: "Chirurgie Pediatrica", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Manea Alina Stefania", s: "Chirurgie Pediatrica", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Oprean Adriana Viorica", s: "Chirurgie Pediatrica", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Putan Iulia Elisabeta", s: "Chirurgie Pediatrica", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Banciu Vasile Stelian", s: "Chirurgie si Ortopedie Pediatrica", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Cumpanasu Ion", s: "Ortopedie Pediatrica", g: "Specialist", c: "spital-pediatrie", t: "medic" },
  { n: "Neamtu Madalina", s: "Ortopedie Pediatrica", g: "Specialist", c: "spital-pediatrie", t: "medic" },
  { n: "Constantin Daniel Marin", s: "Ortopedie Pediatrica", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Galatan Simona", s: "Diabet, nutritie si boli metabolice", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Axinte Roxana Ioana", s: "Dermato-venerologie", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Csillag Andreea", s: "Dermato-venerologie", g: "Specialist", c: "spital-pediatrie", t: "medic" },
  { n: "Sofariu Simona P-va", s: "Endocrinologie", g: "Specialist", c: "spital-pediatrie", t: "medic" },
  { n: "Visa Gabriela", s: "Neurologie Pediatrica", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Crisan Ioana Andreea", s: "Neurologie Pediatrica", g: "Specialist", c: "spital-pediatrie", t: "medic" },
  { n: "Ionica Ciprian C-tin", s: "Oftalmologie", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Constantin Laura", s: "Oftalmologie", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Dudas Doina Mariana", s: "ORL", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Gheorghe Catalin Gabriel", s: "ORL", g: "Specialist", c: "spital-pediatrie", t: "medic" },
  { n: "Muntean Rodica", s: "Pediatrie", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Bogdan Duica Anca Nicoleta", s: "Pediatrie", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Gradinaru Gabriel", s: "Pediatrie", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Radulescu Carmen Maria", s: "Pediatrie", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Matacuta Bogdan Ioana Octavia", s: "Pediatrie", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Vulcan Anca Stefania", s: "Pediatrie", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Cracui Denisa Maria", s: "Pediatrie", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Bacila Nicoleta", s: "Pediatrie", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Sofariu Simona P-va", s: "Pediatrie", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Leuca Raluca Ioana", s: "Pediatrie", g: "Specialist", c: "spital-pediatrie", t: "medic" },
  { n: "Popoiu Razvan", s: "Pediatrie", g: "Specialist", c: "spital-pediatrie", t: "medic" },
  { n: "Opris Valentina", s: "Pediatrie", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Talvan Elena Teodora", s: "Chirurgie BMF", g: "Primar", c: "spital-pediatrie", t: "medic" },
  { n: "Giurgiu Mircea Andrei", s: "Psiholog", g: "-", c: "spital-pediatrie", t: "psiholog" },
  { n: "Nedelcu Susu Andreea Maria", s: "Recuperare, Medicina Fizica si Balneologie", g: "Specialist", c: "spital-pediatrie", t: "medic" },
  { n: "Capata Medina Ileana", s: "Recuperare, Medicina Fizica si Balneologie", g: "Specialist", c: "spital-pediatrie", t: "medic" },

  // --- SPITALUL CLINIC JUDETEAN DE URGENTA (SCJU) ---
  { n: "Porr Corina", s: "Alergologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Birlutiu Victoria", s: "Boli Infectioase", g: "Primar", c: "scju", t: "medic" },
  { n: "Gingaras Cosmina", s: "Boli Infectioase", g: "Primar", c: "scju", t: "medic" },
  { n: "Ilie Adina Elena", s: "Boli Infectioase", g: "Primar", c: "scju", t: "medic" },
  { n: "Stefan Elena Simona", s: "Boli Infectioase", g: "Specialist", c: "scju", t: "medic" },
  { n: "Ghibu Andreea Magdalena", s: "Boli Infectioase", g: "Specialist", c: "scju", t: "medic" },
  { n: "Bitea Cornel Ioan", s: "Cardiologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Cobirje Ioana Maria", s: "Cardiologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Catrina Iulia Bianca", s: "Cardiologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Draghici Dorin", s: "Cardiologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Dumneanu Alexandru", s: "Cardiologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Fiat Emilia Sorina", s: "Cardiologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Lazar Florin Leontin", s: "Cardiologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Lazar Delia", s: "Cardiologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Moga Rodica", s: "Cardiologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Onea Horea Laurentiu", s: "Cardiologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Picu Andreea Maria", s: "Cardiologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Vulcu Raul", s: "Cardiologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Stoia Oana Maria", s: "Cardiologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Teodoru Minodora", s: "Cardiologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Zagoni Cristina Mihaela", s: "Cardiologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Fagetan Mihai Iulian", s: "Chirurgie BMF", g: "Primar", c: "scju", t: "medic" },
  { n: "Barbulescu Bogdan", s: "Chirurgie Generala", g: "Primar", c: "scju", t: "medic" },
  { n: "Bratu Dan", s: "Chirurgie Generala", g: "Primar", c: "scju", t: "medic" },
  { n: "Bardac Ovidiu Dorin", s: "Chirurgie Generala", g: "Primar", c: "scju", t: "medic" },
  { n: "Cretu Dan Gheorghe", s: "Chirurgie Generala", g: "Primar", c: "scju", t: "medic" },
  { n: "Duta Florin Daniel", s: "Chirurgie Generala", g: "Specialist", c: "scju", t: "medic" },
  { n: "Faur Anca", s: "Chirurgie Generala", g: "Primar", c: "scju", t: "medic" },
  { n: "Faur Mihai", s: "Chirurgie Generala", g: "Specialist", c: "scju", t: "medic" },
  { n: "Hulpus Radu", s: "Chirurgie Generala", g: "Primar", c: "scju", t: "medic" },
  { n: "Mohor Calin", s: "Chirurgie Generala", g: "Primar", c: "scju", t: "medic" },
  { n: "Mihetiu Alin Florin", s: "Chirurgie Generala", g: "Primar", c: "scju", t: "medic" },
  { n: "Rotaru Mircea", s: "Chirurgie Generala", g: "Primar", c: "scju", t: "medic" },
  { n: "Tanasescu Ciprian", s: "Chirurgie Generala", g: "Primar", c: "scju", t: "medic" },
  { n: "Sabau Alexandru Dan", s: "Chirurgie Generala", g: "Primar", c: "scju", t: "medic" },
  { n: "Axinte Sergiu", s: "Chirurgie Plastica", g: "Primar", c: "scju", t: "medic" },
  { n: "Helgiu Alina", s: "Chirurgie Plastica", g: "Primar", c: "scju", t: "medic" },
  { n: "Marginean George Ioan", s: "Chirurgie Plastica", g: "Specialist", c: "scju", t: "medic" },
  { n: "Simon Sanda", s: "Chirurgie Plastica", g: "Primar", c: "scju", t: "medic" },
  { n: "Achim Lucian David", s: "Chirurgie Toracica", g: "Primar", c: "scju", t: "medic" },
  { n: "Bardac Ovidiu Dorin", s: "Chirurgie Toracica", g: "Specialist", c: "scju", t: "medic" },
  { n: "Hulpus Radu", s: "Chirurgie Vasculara", g: "Specialist", c: "scju", t: "medic" },
  { n: "Breahna Vadim", s: "Chirurgie Vasculara", g: "Specialist", c: "scju", t: "medic" },
  { n: "Neaga Irina", s: "Chirurgie Vasculara", g: "Specialist", c: "scju", t: "medic" },
  { n: "Ticu Serghei", s: "Chirurgie Vasculara", g: "Specialist", c: "scju", t: "medic" },
  { n: "Mot Alina", s: "Diabet, nutritie si boli metabolice", g: "Primar", c: "scju", t: "medic" },
  { n: "Sitterli Natea Carmen Narcisa", s: "Diabet, nutritie si boli metabolice", g: "Primar", c: "scju", t: "medic" },
  { n: "Dinca Georgiana", s: "Diabet, nutritie si boli metabolice", g: "Primar", c: "scju", t: "medic" },
  { n: "Podar Oana Maria", s: "Diabet, nutritie si boli metabolice", g: "Primar", c: "scju", t: "medic" },
  { n: "Calutiu Nicoleta", s: "Diabet, nutritie si boli metabolice", g: "Primar", c: "scju", t: "medic" },
  { n: "Baldovin Ioana", s: "Dermato-venerologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Iancu Mariana Gabriela", s: "Dermato-venerologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Maniu Horia", s: "Dermato-venerologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Vilsan Codrut Gabriel", s: "Dermato-venerologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Stanciu Mihaela", s: "Endocrinologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Boicean Loredana Camelia", s: "Endocrinologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Draghici Ionela Diana", s: "Endocrinologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Lebada Ioana Codruta", s: "Endocrinologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Boiceanu Adrian", s: "Gastroenterologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Baluta Teodora Mihaela", s: "Gastroenterologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Mocanu Dragos", s: "Gastroenterologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Prisca Diana Paraschiva", s: "Gastroenterologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Maxim Monica", s: "Gastroenterologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Catana Alina", s: "Hematologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Flucus Ofelia", s: "Hematologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Bus Cristina Mihaela", s: "Hematologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Mihaila Romeo", s: "Hematologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Mondoc Lidia Maria", s: "Hematologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Lienerth Doris", s: "Hematologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Beca Corina", s: "Medicina Interna", g: "Primar", c: "scju", t: "medic" },
  { n: "Havarneanu Bica Daniela", s: "Medicina Interna", g: "Primar", c: "scju", t: "medic" },
  { n: "Cipaian Calin", s: "Medicina Interna", g: "Primar", c: "scju", t: "medic" },
  { n: "Petrascu Ovidiu", s: "Medicina Interna", g: "Primar", c: "scju", t: "medic" },
  { n: "Solomon Adelaida Simina", s: "Medicina Interna", g: "Primar", c: "scju", t: "medic" },
  { n: "Dascalu Daciana", s: "Medicina Interna", g: "Primar", c: "scju", t: "medic" },
  { n: "Tudor Victor Constantin", s: "Medicina Interna", g: "Primar", c: "scju", t: "medic" },
  { n: "Orga Dumitriu Dan Ioan", s: "Medicina Interna", g: "Primar", c: "scju", t: "medic" },
  { n: "Mitea Sorin Ioan", s: "Nefrologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Cotarla Liviu", s: "Nefrologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Popa Livia", s: "Nefrologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Popa Livia Mirela", s: "Nefrologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Saceleanu Mircea Vicentiu", s: "Neurochirurgie", g: "Primar", c: "scju", t: "medic" },
  { n: "Fagarasi Titus", s: "Neurochirurgie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Cindea Cosmin", s: "Neurochirurgie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Moscu Bianca", s: "Neurologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Cuibus Liliana", s: "Neurologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Mutu Catalin Cosmin", s: "Neurologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Prodan Liiana Carmen", s: "Neurologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Roman Filip Carmen Corina", s: "Neurologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Vladoiu Maria Gabriela", s: "Neurologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Stingaciu Anca Rafila", s: "Neurologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Bartos Irina Roxana", s: "Oftalmologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Mihai Elena", s: "Oftalmologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Tudor Corina", s: "Oftalmologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Popa Elena Dorina", s: "Oftalmologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Badescu Tudor", s: "Obstetrica-Ginecologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Balasoiu Ionel", s: "Obstetrica-Ginecologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Chicea Radu", s: "Obstetrica-Ginecologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Codru Marian Valeriu", s: "Obstetrica-Ginecologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Coracioni Ilonca", s: "Obstetrica-Ginecologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Ginfalean Georgeta", s: "Obstetrica-Ginecologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Ispasoiu Iulian Florin", s: "Obstetrica-Ginecologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Pop Lodromanean Diana", s: "Obstetrica-Ginecologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Muresan Ioan Olimpiu", s: "Obstetrica-Ginecologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Cimpean Tulea Andreea Alexandra", s: "Obstetrica-Ginecologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Popescu Dragos", s: "Obstetrica-Ginecologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Popescu Elena Cristina", s: "Obstetrica-Ginecologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Popa Nicoleta Lucica", s: "Obstetrica-Ginecologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Suveica Radu", s: "Obstetrica-Ginecologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Voiasciuc Valentin", s: "Obstetrica-Ginecologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Taroi Cristian", s: "Obstetrica-Ginecologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Cipaian Alexandra", s: "Oncologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Coca Ramona", s: "Oncologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Coca Rafaela Maria", s: "Oncologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Patran Monica", s: "Oncologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Zifceac Paulina", s: "Oncologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Chialda Mihaela", s: "ORL", g: "Primar", c: "scju", t: "medic" },
  { n: "Rusu Gabriel", s: "ORL", g: "Primar", c: "scju", t: "medic" },
  { n: "Popescu Alin Tudor", s: "ORL", g: "Primar", c: "scju", t: "medic" },
  { n: "Ermacov Liliana", s: "ORL", g: "Specialist", c: "scju", t: "medic" },
  { n: "Dascalu Iulian Alin", s: "ORL", g: "Specialist", c: "scju", t: "medic" },
  { n: "Ihora Benedek Iulia Maria", s: "Ortopedie", g: "Primar", c: "scju", t: "medic" },
  { n: "Lupean Adrian", s: "Ortopedie", g: "Primar", c: "scju", t: "medic" },
  { n: "Mohor Cosmin", s: "Ortopedie", g: "Primar", c: "scju", t: "medic" },
  { n: "Sopon Mircea Ciprian", s: "Ortopedie", g: "Primar", c: "scju", t: "medic" },
  { n: "Stanciu Teodor", s: "Ortopedie", g: "Primar", c: "scju", t: "medic" },
  { n: "Bocea Bogdan Axente", s: "Ortopedie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Ion Nicolas Catalin Ionut", s: "Ortopedie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Carja Alina Mihaela", s: "Psihiatrie", g: "Primar", c: "scju", t: "medic" },
  { n: "Chicea Liana", s: "Reumatologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Buric Nicoleta", s: "Reumatologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Grigore Nicolae", s: "Urologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Mihai Ionela", s: "Urologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Tohati Tiberiu", s: "Urologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Bumbulut Bogdan", s: "Urologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Diaconu Cosmina", s: "Recuperare, Medicina Fizica si Balneologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Pintea Alina Liliana", s: "Recuperare, Medicina Fizica si Balneologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Popa Florina", s: "Recuperare, Medicina Fizica si Balneologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Canciu Adriana Maria", s: "Recuperare, Medicina Fizica si Balneologie", g: "Specialist", c: "scju", t: "medic" },
  { n: "Giurca Dan", s: "Recuperare, Medicina Fizica si Balneologie", g: "Primar", c: "scju", t: "medic" },
  { n: "Stefan Simina Ancuta", s: "Recuperare, Medicina Fizica si Balneologie", g: "Specialist", c: "scju", t: "medic" },

  // --- SPITALUL DE PNEUMOFTIZIOLOGIE ---
  { n: "Draghila Ioan", s: "Pneumologie", g: "Primar", c: "spital-pneumo", t: "medic" },
  { n: "Buga Sebastian Aristide", s: "Pneumologie", g: "Primar", c: "spital-pneumo", t: "medic" },
  { n: "Chichirita Adela", s: "Pneumologie", g: "Primar", c: "spital-pneumo", t: "medic" },
  { n: "Danciu Lavinia", s: "Pneumologie", g: "Primar", c: "spital-pneumo", t: "medic" },
  { n: "Scridon Maria Elena", s: "Pneumologie", g: "Primar", c: "spital-pneumo", t: "medic" },
  { n: "Radulescu Adriana", s: "Pneumologie", g: "Primar", c: "spital-pneumo", t: "medic" },
  { n: "Metiu Joldes Oana Elena", s: "Pneumologie", g: "Primar", c: "spital-pneumo", t: "medic" },
  { n: "Lucuta Ovidiu Traian", s: "Pneumologie", g: "Primar", c: "spital-pneumo", t: "medic" },
  { n: "Drutu Gabriela Dorina", s: "Pneumologie", g: "Specialist", c: "spital-pneumo", t: "medic" },
  { n: "Simina Iulia Ida", s: "Pneumologie", g: "Primar", c: "spital-pneumo", t: "medic" },
  { n: "Tecoanta Adina Luminita", s: "Pneumologie", g: "Specialist", c: "spital-pneumo", t: "medic" },
  { n: "Sudrijan Ionela Monica", s: "Pneumologie", g: "Specialist", c: "spital-pneumo", t: "medic" },
  { n: "Dancila Darius-Dumitru", s: "Pneumologie", g: "Specialist", c: "spital-pneumo", t: "medic" },
  { n: "Oaida Iulia-Emanuela", s: "Pneumologie", g: "Specialist", c: "spital-pneumo", t: "medic" },
  { n: "Mustatea Simina", s: "Pneumologie", g: "Specialist", c: "spital-pneumo", t: "medic" },
  { n: "Dirzu Vlad Ioan", s: "Pneumologie", g: "Specialist", c: "spital-pneumo", t: "medic" },
  { n: "Orlandea Laura Stefana", s: "Psiholog", g: "-", c: "spital-pneumo", t: "psiholog" },
  { n: "Petru Camelia", s: "Neurologie", g: "Primar", c: "spital-pneumo", t: "medic" },
  { n: "Joarza Alina Adela", s: "Neurologie", g: "Specialist", c: "spital-pneumo", t: "medic" },
  { n: "Iuga Madalina", s: "Neurologie", g: "Specialist", c: "spital-pneumo", t: "medic" },
  { n: "Piso Cristina", s: "Neurologie Pediatrica", g: "Primar", c: "spital-pneumo", t: "medic" },
  { n: "Henzel Paula Sorina", s: "Neurologie Pediatrica / NPI", g: "Primar/Specialist", c: "spital-pneumo", t: "medic" },
  { n: "Rotar Oana Teodora", s: "Medicina Interna", g: "Specialist", c: "spital-pneumo", t: "medic" },

  // --- SPITALUL DE PSIHIATRIE ---
  { n: "Voulgaropoulos Agata Mirela", s: "Psihiatrie", g: "Primar", c: "spital-psih", t: "medic" },
  { n: "Mitrea Felicia", s: "Psihiatrie", g: "Primar", c: "spital-psih", t: "medic" },
  { n: "Duica Lavinia", s: "Psihiatrie", g: "Primar", c: "spital-psih", t: "medic" },
  { n: "Popa Mircea Bogdan", s: "Psihiatrie", g: "Primar", c: "spital-psih", t: "medic" },
  { n: "Rusu Silvia", s: "Psihiatrie", g: "Primar", c: "spital-psih", t: "medic" },
  { n: "Anghel Claudia Elena", s: "Psihiatrie", g: "Primar", c: "spital-psih", t: "medic" },
  { n: "Cornea Monica", s: "Psihiatrie", g: "Specialist", c: "spital-psih", t: "medic" },
  { n: "Selejan Adrian", s: "Psihiatrie", g: "Primar", c: "spital-psih", t: "medic" },
  { n: "Butnarasu Simona", s: "Psihiatrie", g: "Specialist", c: "spital-psih", t: "medic" },
  { n: "Oroian Cristina Gabriela", s: "Psihiatrie", g: "Primar", c: "spital-psih", t: "medic" },
  { n: "Muntean Cosmina", s: "Psihiatrie", g: "Primar", c: "spital-psih", t: "medic" },
  { n: "Sabau Bogdan Alin", s: "Psihiatrie", g: "Primar", c: "spital-psih", t: "medic" },
  { n: "Bacila Ionut Ciprian", s: "Psihiatrie", g: "Primar", c: "spital-psih", t: "medic" },
  { n: "Sendriuc Ovidiu Nicolae", s: "Psihiatrie", g: "Specialist", c: "spital-psih", t: "medic" },
  { n: "Zaharia Carmen Elena", s: "Psihiatrie", g: "Primar", c: "spital-psih", t: "medic" },
  { n: "Petru Camelia", s: "Psihiatrie", g: "Specialist", c: "spital-psih", t: "medic" },
  { n: "Decean Marius", s: "Psihiatrie Pediatrica", g: "Primar", c: "spital-psih", t: "medic" },
  { n: "Pavel Mihaela", s: "Psiholog", g: "-", c: "spital-psih", t: "psiholog" },
  { n: "Popa Lucia Maria", s: "Psiholog", g: "-", c: "spital-psih", t: "psiholog" },
  { n: "Nicoara Maria Daniela", s: "Psiholog", g: "-", c: "spital-psih", t: "psiholog" },
  { n: "Mara Tomina", s: "Psiholog", g: "-", c: "spital-psih", t: "psiholog" },
  { n: "Laslau Diana Maria", s: "Psiholog", g: "-", c: "spital-psih", t: "psiholog" },
  { n: "Marginean Hurdubelea Mihaela", s: "Psiholog", g: "-", c: "spital-psih", t: "psiholog" },
  { n: "Stroia Irina Liana", s: "Psiholog", g: "-", c: "spital-psih", t: "psiholog" },
  { n: "Vulcu Radu Iustin", s: "Psiholog", g: "-", c: "spital-psih", t: "psiholog" },
  { n: "Gaja Liviu", s: "Psiholog", g: "-", c: "spital-psih", t: "psiholog" },
  { n: "Orlandea Laura Stefana", s: "Psiholog", g: "-", c: "spital-psih", t: "psiholog" },
  { n: "Luca Silvia", s: "Recuperare, Medicina Fizica si Balneologie", g: "Primar", c: "spital-psih", t: "medic" },
  { n: "Micu Elena Claudia", s: "Recuperare, Medicina Fizica si Balneologie", g: "Primar", c: "spital-psih", t: "medic" },
  { n: "Dima Vasile Viorel", s: "Recuperare, Medicina Fizica si Balneologie", g: "Primar", c: "spital-psih", t: "medic" },
  { n: "Panzariu Madalina Andreea", s: "Kinetoterapie", g: "-", c: "spital-psih", t: "kinetoterapeut" },

  // --- SPITALUL GENERAL CF ---
  { n: "Barabas Francisc Aurelian", s: "Chirurgie Generala", g: "Primar", c: "spital-cf", t: "medic" },
  { n: "Ucenic Ovidiu Mircea", s: "Chirurgie Generala", g: "Primar", c: "spital-cf", t: "medic" },
  { n: "Hulpus Andreea Tania", s: "Chirurgie Plastica", g: "Specialist", c: "spital-cf", t: "medic" },
  { n: "Candea Margareta Elena", s: "Medicina Interna", g: "Primar", c: "spital-cf", t: "medic" },
  { n: "Nistor Adrian Petru", s: "Cardiologie", g: "Primar", c: "spital-cf", t: "medic" },
  { n: "Negrea Mihai Octavian", s: "Cardiologie", g: "Specialist", c: "spital-cf", t: "medic" },
  { n: "Opris Anca Maria", s: "Dermato-venerologie", g: "Primar", c: "spital-cf", t: "medic" },
  { n: "Luca Silvia", s: "Medicina Interna", g: "Primar", c: "spital-cf", t: "medic" },
  { n: "Damian Alina Daniela", s: "Medicina Interna", g: "Specialist", c: "spital-cf", t: "medic" },
  { n: "Iacob Rares Florin", s: "Medicina Fizica si Reabilitare", g: "Specialist", c: "spital-cf", t: "medic" },
  { n: "Tanase Alexandra", s: "Neurologie", g: "Specialist", c: "spital-cf", t: "medic" },
  { n: "Stupariu Adrian Laurentiu", s: "Oftalmologie", g: "Primar", c: "spital-cf", t: "medic" },
  { n: "Frandes Iulia", s: "ORL", g: "Primar", c: "spital-cf", t: "medic" },
  { n: "Coseriu Frijan Georgeta Lucia", s: "ORL", g: "Primar", c: "spital-cf", t: "medic" },
  { n: "Artimon Mihaela Henrieta", s: "Psihiatrie", g: "Primar", c: "spital-cf", t: "medic" },
  { n: "Jugarean Andreea Ileana", s: "Psiholog", g: "-", c: "spital-cf", t: "psiholog" },

  // --- SPITALUL MUNICIPAL MEDIAS ---
  { n: "Bogdan Aurelia", s: "Boli Infectioase", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Varaticeanu Alexandru Lucian", s: "Boli Infectioase", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Burian Ioan", s: "Cardiologie", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Calin Elena Antonela", s: "Cardiologie", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Burghelea Bogdan", s: "Chirurgie Generala", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Paralescu Raul Adrian", s: "Chirurgie Generala", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Mursa Adrian", s: "Chirurgie Generala", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Pastiu Adrian Ovidiu", s: "Chirurgie Generala", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Davel Ioana Adriana", s: "Chirurgie Generala", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Nester Gabriel", s: "Chirurgie Generala", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Ngwenya Mishack", s: "Chirurgie Generala", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Burghelea Daniela", s: "Chirurgie Pediatrica", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Stanciu Lacrima Teodora", s: "Endocrinologie", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Miron Veronica", s: "Gastroenterologie", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Plescuta Roxana", s: "Gastroenterologie", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Morari Svetlana", s: "Medicina Interna", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Albu Elena Roxana", s: "Medicina Interna", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Nemes Noemi Dalma", s: "Medicina Interna", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Feier Cristian Dorian", s: "Medicina Interna", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Dancu Radu George Sevastian", s: "Medicina Interna / Hematologie", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Harabor Georgiana", s: "Recuperare, Medicina Fizica si Balneologie", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Trambitas Grigore Dan", s: "Recuperare, Medicina Fizica si Balneologie", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Somesan Livia Ionela", s: "Neurologie", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Godo Eniko", s: "Neurologie", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Vaso Edvin", s: "Obstetrica-Ginecologie", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Truta Jan", s: "Obstetrica-Ginecologie", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Corbeanu Onoriu", s: "Obstetrica-Ginecologie", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Mihut Bogdan Ioan", s: "Obstetrica-Ginecologie", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Juncu Victor", s: "Obstetrica-Ginecologie", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Rachita Mihaela Maria", s: "Obstetrica-Ginecologie", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Stefan Anda Simina", s: "ORL", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Balin Alexandru Gheorghe", s: "ORL", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Ahmad Cezar", s: "Ortopedie", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Roman Ciprian Oliviu", s: "Ortopedie", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Oprisan Andrei", s: "Ortopedie", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Todoran Liviu Radu", s: "Ortopedie", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Fiser Lucian Daniel", s: "Oncologie", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Ilies Sabina", s: "Pediatrie", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Sarbu Monica", s: "Pediatrie", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Dolgani Svetlana", s: "Pediatrie", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Stanciu Maria Georgiana", s: "Pediatrie", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Szabo Chiriac Eveline Christine", s: "Pneumologie", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Campean Ioan Marius", s: "Pneumologie", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Holerga Ioana Iuliana", s: "Psihiatrie", g: "Specialist", c: "spital-medias", t: "medic" },
  { n: "Nicola Theodor Alexandru", s: "Urologie", g: "Primar", c: "spital-medias", t: "medic" },
  { n: "Marica Alin", s: "Urologie", g: "Specialist", c: "spital-medias", t: "medic" },

  // --- SPITALUL ORASENESC AGNITA ---
  { n: "Vidrighin Nicolae Ilie", s: "Chirurgie Generala", g: "Specialist", c: "spital-agnita", t: "medic" },
  { n: "Popa Sorin Radu", s: "Medicina Interna", g: "Specialist", c: "spital-agnita", t: "medic" },
  { n: "Glod Eugen Vasile", s: "Obstetrica-Ginecologie", g: "Primar", c: "spital-agnita", t: "medic" },
  { n: "Sotir Setel Codruta", s: "Pediatrie", g: "Specialist", c: "spital-agnita", t: "medic" },
  { n: "Marin Marcela Adina Rodica", s: "Psihiatrie", g: "Specialist", c: "spital-agnita", t: "medic" },
  { n: "Eremeev Spiridon", s: "Chirurgie Generala", g: "Primar", c: "spital-agnita", t: "medic" },

  // --- SPITALUL ORASENESC CISNADIE ---
  { n: "Baltat Georgiana", s: "Cardiologie", g: "Specialist", c: "spital-cisnadie", t: "medic" },
  { n: "Lupean Laura Maria", s: "Endocrinologie", g: "Specialist", c: "spital-cisnadie", t: "medic" },
  { n: "Isaila Radu", s: "Medicina Interna", g: "Primar", c: "spital-cisnadie", t: "medic" },
  { n: "Nistor Lacramioara", s: "Medicina Interna", g: "Primar", c: "spital-cisnadie", t: "medic" },
  { n: "Pop Anamaria", s: "Medicina Interna", g: "Primar", c: "spital-cisnadie", t: "medic" },
  { n: "Ban Maria Cristina", s: "Medicina Interna / Reumatologie", g: "Primar/Specialist", c: "spital-cisnadie", t: "medic" },
  { n: "Piloiu Claudia", s: "Gastroenterologie", g: "Specialist", c: "spital-cisnadie", t: "medic" },
  { n: "Popa Andreea Teodora", s: "Obstetrica-Ginecologie", g: "Primar", c: "spital-cisnadie", t: "medic" },
  { n: "Solomon Nicoleta", s: "ORL", g: "Primar", c: "spital-cisnadie", t: "medic" },
  { n: "Roth Cristina Ioana", s: "Oftalmologie", g: "Primar", c: "spital-cisnadie", t: "medic" },
  { n: "Novac Mircea Antoniu", s: "Pediatrie", g: "Primar", c: "spital-cisnadie", t: "medic" },
  { n: "Popa Monica Carmen", s: "Psihiatrie", g: "Primar", c: "spital-cisnadie", t: "medic" },
  { n: "Lazaroaie Ana", s: "Neurologie", g: "Primar", c: "spital-cisnadie", t: "medic" },
  { n: "Zaica Svetlana", s: "Neurologie", g: "Specialist", c: "spital-cisnadie", t: "medic" },
  { n: "Mardari Bogdan Catalin", s: "Urologie", g: "Primar", c: "spital-cisnadie", t: "medic" },
  { n: "Orlandea Laura Stefana", s: "Psiholog", g: "-", c: "spital-cisnadie", t: "psiholog" },

  // --- TURCU TEODORA DV ---
  { n: "Turcu Teodora", s: "Dermato-venerologie", g: "Primar", c: "turcu-dv", t: "medic" },

  // --- DR. TODAN DV ---
  { n: "Todan Liliana Elena", s: "Dermato-venerologie", g: "Specialist", c: "todan-dv", t: "medic" },

  // --- UNIMED ---
  { n: "Muntean Cristina", s: "Obstetrica-Ginecologie", g: "Specialist", c: "unimed", t: "medic" },
  { n: "Muresan Ioan Olimpiu", s: "Obstetrica-Ginecologie", g: "Primar", c: "unimed", t: "medic" },

  // --- VERES OANA DIABET ---
  { n: "Veres Oana", s: "Diabet, nutritie si boli metabolice", g: "Primar", c: "veres-diabet", t: "medic" },

  // --- SPITALUL CLINIC DE PEDIATRIE SIBIU (servicii conexe) ---
  { n: "Giurgiu Mircea Andrei", s: "Diabet zaharat, Neurologie pediatrica", g: "-", c: "spital-pediatrie", t: "psiholog" },

  // --- DR. COSTACHE-BARB CRISTINA (Diabet) ---
  { n: "Costache-Barb Cristina", s: "Diabet, nutritie si boli metabolice", g: "Specialist", c: "costache-barb", t: "medic" },

  // --- DR. MESTER ELENA LAVINIA (Pediatrie) ---
  { n: "Mester Elena Lavinia", s: "Pediatrie", g: "Primar", c: "mester-ped", t: "medic" },
];
